version: '3.4'

services:
  boostproject_postgres:
    image: postgres:15.1

  boostproject_rabbitmq:
    image: rabbitmq:3.10.7-management

  boostproject_api:
    image: ${DOCKER_REGISTRY-}boostprojectapi
    build:
      context: .
      dockerfile: Systems/Api/BoostProject.Api/Dockerfile
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=7000
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Passw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/BoostProject.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - boostproject_postgres
      - boostproject_rabbitmq
      - boostproject_authorizationserver
      - boostproject_resourceserver

  boostproject_chatsapi:
    image: ${DOCKER_REGISTRY-}boostprojectchatsapi
    build:
      context: .
      dockerfile: Systems/Api/BoostProject.ChatsApi/Dockerfile
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=7001
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Passw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/BoostProject.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - boostproject_postgres
      - boostproject_authorizationserver
      - boostproject_resourceserver

  boostproject_emailworker:
    image: ${DOCKER_REGISTRY-}boostprojectemailworker
    build:
      context: .
      dockerfile: Systems/EmailWorker/BoostProject.EmailWorker/Dockerfile
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=9000
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Passw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/BoostProject.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - boostproject_postgres
      - boostproject_rabbitmq
      - boostproject_api

  boostproject_authorizationserver:
    image: ${DOCKER_REGISTRY-}boostprojectauthorizationserver
    build:
      context: .
      dockerfile: Systems/AuthotizationServer/BoostProject.AuthorizationServer/Dockerfile
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=8000
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Passw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/BoostProject.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - boostproject_postgres

  boostproject_resourceserver:
    image: ${DOCKER_REGISTRY-}boostprojectresourceserver
    build:
      context: .
      dockerfile: Systems/AuthotizationServer/BoostProject.ResourceServer/Dockerfile
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=8001 
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Passw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/BoostProject.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - boostproject_postgres
      - boostproject_authorizationserver

